### ISSUE TITLE
some URL to telegraph, some not, don't know why.

### ISSUE THREAD

**Issue by QQ-War** [ehForwarderBot/efb-mp-instantview-middleware#1]
the first one didn't, while the second success.
I didn't find the difference.

Tay 07 21:55:03 computer_name ehforwarderbot[157844]:     received event: EventGroupMsg
Tay 07 21:55:03 computer_name ehforwarderbot[157844]: {'event': 'EventGroupMsg', 'robot_wxid': '删除', 'robot_name': '', 'type': 'share', 'from_wxid': '删除', 'from_name': '删除', 'final_from_wxid': '删除', 'final_from_name': '删除', 'to_wxid': '删除', 'msgid': '1772797919', 'msg': '<msg>\r\n    <appmsg appid="" sdkver="0">\r\n        <title><![CDATA[删除]]></title>\r\n        <des><![CDATA[删除]]></des>\r\n        <action></action>\r\n        <type>5</type>\r\n        <showtype>0</showtype>\r\n        <content></content>\r\n        <url><![CDATA[删除URL]]></url>\r\n        <lowurl></lowurl>\r\n        <appattach>\r\n            <totallen>0</totallen>\r\n            <attachid></attachid>\r\n            <fileext></fileext>\r\n\r\n      <tpthumburl><![CDATA[删除URL]]></tpthumburl>\r\n      <tpthumbaeskey><![CDATA[]]></tpthumbaeskey>\r\n      <tpauthkey><![CDATA[]]></tpauthkey>\r\n      <tpthumblength><![CDATA[0]]></tpthumblength>\r\n      <tpthumbmd5><![CDATA[]]></tpthumbmd5>\r\n      <tpthumbwidth><![CDATA[]]></tpthumbwidth>\r\n      <tpthumbheight><![CDATA[]]></tpthumbheight>\r\n\r\n        </appattach>\r\n        <extinfo></extinfo>\r\n        <thumburl><![CDATA[]]></thumburl>\r\n    </appmsg>\r\n    <fromusername><![CDATA[25984984653187515@openim]]></fromusername>\r\n    <extshowtype></extshowtype>\r\n    <appinfo>\r\n            <version></version>\r\n            <appname></appname>\r\n            <isforceupdate></isforceupdate>\r\n    </appinfo>\r\n</msg>'}
Tay 07 21:55:03 computer_name ehforwarderbot[157844]: 2022-04-07 21:55:03,889 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:91)
Tay 07 21:55:03 computer_name ehforwarderbot[157844]:     [None] Slave message delivered to ETM.

Tay 07 21:59:19 computer_name ehforwarderbot[157844]: {'event': 'EventGroupMsg', 'robot_wxid': '删除', 'robot_name': '', 'type': 'share', 'from_wxid': '删除', 'from_name': '删除', 'final_from_wxid': '删除', 'final_from_name': '删除', 'to_wxid': '删除', 'msgid': '1772797920', 'msg': '<msg>\r\n    <appmsg appid="" sdkver="0">\r\n        <title><![CDATA[删除]]></title>\r\n        <des><![CDATA[删除]]></des>\r\n        <action></action>\r\n        <type>5</type>\r\n        <showtype>0</showtype>\r\n        <content></content>\r\n        <url><![CDATA[删除URL]]></url>\r\n        <lowurl></lowurl>\r\n        <appattach>\r\n            <totallen>0</totallen>\r\n            <attachid></attachid>\r\n            <fileext></fileext>\r\n\r\n      <tpthumburl><![CDATA[删除URL]]></tpthumburl>\r\n      <tpthumbaeskey><![CDATA[]]></tpthumbaeskey>\r\n      <tpauthkey><![CDATA[]]></tpauthkey>\r\n      <tpthumblength><![CDATA[0]]></tpthumblength>\r\n      <tpthumbmd5><![CDATA[]]></tpthumbmd5>\r\n      <tpthumbwidth><![CDATA[]]></tpthumbwidth>\r\n      <tpthumbheight><![CDATA[]]></tpthumbheight>\r\n\r\n        </appattach>\r\n        <extinfo></extinfo>\r\n        <thumburl><![CDATA[]]></thumburl>\r\n    </appmsg>\r\n    <fromusername><![CDATA[25984984653187515@openim]]></fromusername>\r\n    <extshowtype></extshowtype>\r\n    <appinfo>\r\n            <version></version>\r\n            <appname></appname>\r\n            <isforceupdate></isforceupdate>\r\n    </appinfo>\r\n</msg>'}
Tay 07 21:59:19 computer_name ehforwarderbot[157844]: 2022-04-07 21:59:19,167 [DEBUG]: urllib3.connectionpool (connectionpool._get_conn; connectionpool.py:266)
Tay 07 21:59:19 computer_name ehforwarderbot[157844]:     Resetting dropped connection: mp.weixin.qq.com
Tay 07 21:59:21 computer_name ehforwarderbot[157844]: 2022-04-07 21:59:21,216 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:428)
Tay 07 21:59:21 computer_name ehforwarderbot[157844]:     https://mp.weixin.qq.com:443 "GET /s?t=pages/video_detail_new&scene=1&vid=wxv_2338765966769258496&__biz=MzI0NjA4MzY5OA==&mid=2247502084&idx=3&sn=e51dc6aa941fbdf1e42ec4e0425aba38&vidsn= HTTP/1.1" 200 23072
Tay 07 21:59:21 computer_name ehforwarderbot[157844]: 2022-04-07 21:59:21,240 [DEBUG]: urllib3.connectionpool (connectionpool._new_conn; connectionpool.py:957)
Tay 07 21:59:21 computer_name ehforwarderbot[157844]:     Starting new HTTPS connection (3): api.telegra.ph:443
Tay 07 21:59:21 computer_name ehforwarderbot[157844]: 2022-04-07 21:59:21,990 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:428)
Tay 07 21:59:21 computer_name ehforwarderbot[157844]:     https://api.telegra.ph:443 "POST /createPage HTTP/1.1" 200 243
Tay 07 21:59:21 computer_name ehforwarderbot[157844]: 2022-04-07 21:59:21,992 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:91)
Tay 07 21:59:21 computer_name ehforwarderbot[157844]:     [None] Slave message delivered to ETM.

**Comment by QQ-War** [comment]
如下四个链接，第一个链接就稳定不转telegraph。

[3天前，这个小国，狠狠“帮美国教训”了中国和俄罗斯？: http://mp.weixin.qq.com/s?__biz=MjM5OTYwOTM0Nw==&mid=2650229747&idx=1&sn=366826a0aa3a63dfb69a1ec08d6dbde3&chksm=bf3b3e9f884cb78903777eeab58841dfd16a4344276caa9b0b20dd39cfea3fa1b2d6df40e67c#rd]



[“宁可自己遭罪也不想看到它们受伤害”: http://mp.weixin.qq.com/s?__biz=MjM5OTYwOTM0Nw==&mid=2650229747&idx=3&sn=d104846d1fc1602bc1d26183ac836b0c&chksm=bf3b3e9f884cb789949fe700f180e0181768f2eda72a1acd92e01889e7c9fe959ec8d06820ee#rd]



[魔幻现实丨每日一冷: http://mp.weixin.qq.com/s?__biz=MjM5OTYwOTM0Nw==&mid=2650229747&idx=6&sn=924a311436255160975df87ced11a0ea&chksm=bf3b3e9f884cb7897936414871e663a0f10a2a045a6afa8aae93a277b543e627ab851585f7ca#rd]



[上海努力做到蔬菜礼包全覆盖、深圳建立国内首个宠物方舱、少林寺进军房地产丨酷玩日爆: http://mp.weixin.qq.com/s?__biz=MjM5OTYwOTM0Nw==&mid=2650229747&idx=7&sn=7e9388084fd7d3d6eb346f60537724e3&chksm=bf3b3e9f884cb7892d84dcd85691508971b4aefde5f0a466de614b61a672115fd5887157e422#rd]

**Comment by QQ-War** [comment]
更多日志，可以看到是middleware失败。

Tay 09 09:36:48 computername ehforwarderbot[173558]: {'event': 'EventFriendMsg', ********, 'msg': '<?xml version="1.0"?>\r\n<msg>\r\n\t<appmsg appid="" sdkver="0">\r\n\t\t<title>3天前，这个小国，狠狠“帮美国教训”了中国和俄罗斯？</title>\r\n\t\t<des>美国“代言人”立陶宛：叫唤得有多凶，脸打得就有多疼</des>\r\n\t\t<username />\r\n\t\t<action>view</action>\r\n\t\t<type>5</type>\r\n\t\t<showtype>0</showtype>\r\n\t\t<content />\r\n\t\t<url>http://mp.weixin.qq.com/s?__biz=MjM5OTYwOTM0Nw==&amp;mid=2650229747&amp;idx=1&amp;sn=366826a0aa3a63dfb69a1ec08d6dbde3&amp;chksm=bf3b3e9f884cb78903777eeab58841dfd16a4344276caa9b0b20dd39cfea3fa1b2d6df40e67c#rd</url>\r\n\t\t<lowurl />\r\n\t\t<forwardflag>0</forwardflag>\r\n\t\t<dataurl />\r\n\t\t<lowdataurl />\r\n\t\t<contentattr>0</contentattr>\r\n\t\t<streamvideo>\r\n\t\t\t<streamvideourl />\r\n\t\t\t<streamvideototaltime>0</streamvideototaltime>\r\n\t\t\t<streamvideotitle />\r\n\t\t\t<streamvideowording />\r\n\t\t\t<streamvideoweburl />\r\n\t\t\t<streamvideothumburl />\r\n\t\t\t<streamvideoaduxinfo />\r\n\t\t\t<streamvideopublishid />\r\n\t\t</streamvideo>\r\n\t\t<canvasPageItem>\r\n\t\t\t<canvasPageXml><![CDATA[]]></canvasPageXml>\r\n\t\t</canvasPageItem>\r\n\t\t<appattach>\r\n\t\t\t<totallen>0</totallen>\r\n\t\t\t<attachid />\r\n\t\t\t<cdnattachurl />\r\n\t\t\t<emoticonmd5></emoticonmd5>\r\n\t\t\t<aeskey></aeskey>\r\n\t\t\t<fileext />\r\n\t\t\t<islargefilemsg>0</islargefilemsg>\r\n\t\t</appattach>\r\n\t\t<extinfo />\r\n\t\t<androidsource>3</androidsource>\r\n\t\t<sourceusername>gh_f33ea5eaf126</sourceusername>\r\n\t\t<sourcedisplayname>酷玩实验室</sourcedisplayname>\r\n\t\t<commenturl />\r\n\t\t<thumburl>https://mmbiz.qpic.cn/mmbiz_jpg/zYDoI5AgJrvIFrtDgDDZJWZtrA18XsaT1RKiaCibZmF9N0qhly32b13MuZ8N0qKaHmElGmYhHGTvicwL3rVLdLN0g/300?wxtype=jpeg&amp;wxfrom=0</thumburl>\r\n\t\t<mediatagname />\r\n\t\t<messageaction><![CDATA[]]></messageaction>\r\n\t\t<messageext><![CDATA[]]></messageext>\r\n\t\t<emoticongift>\r\n\t\t\t<packageflag>0</packageflag>\r\n\t\t\t<packageid />\r\n\t\t</emoticongift>\r\n\t\t<emoticonshared>\r\n\t\t\t<packageflag>0</packageflag>\r\n\t\t\t<packageid />\r\n\t\t</emoticonshared>\r\n\t\t<designershared>\r\n\t\t\t<designeruin>0</designeruin>\r\n\t\t\t<designername>null</designername>\r\n\t\t\t<designerrediretcturl>null</designerrediretcturl>\r\n\t\t</designershared>\r\n\t\t<emotionpageshared>\r\n\t\t\t<tid>0</tid>\r\n\t\t\t<title>null</title>\r\n\t\t\t<desc>null</desc>\r\n\t\t\t<iconUrl>null</iconUrl>\r\n\t\t\t<secondUrl>null</secondUrl>\r\n\t\t\t<pageType>0</pageType>\r\n\t\t</emotionpageshared>\r\n\t\t<webviewshared>\r\n\t\t\t<shareUrlOriginal />\r\n\t\t\t<shareUrlOpen />\r\n\t\t\t<jsAppId />\r\n\t\t\t<publisherId />\r\n\t\t</webviewshared>\r\n\t\t<template_id />\r\n\t\t<md5 />\r\n\t\t<weappinfo>\r\n\t\t\t<username />\r\n\t\t\t<appid />\r\n\t\t\t<appservicetype>0</appservicetype>\r\n\t\t\t<secflagforsinglepagemode>0</secflagforsinglepagemode>\r\n\t\t\t<videopageinfo>\r\n\t\t\t\t<thumbwidth>0</thumbwidth>\r\n\t\t\t\t<thumbheight>0</thumbheight>\r\n\t\t\t\t<fromopensdk>0</fromopensdk>\r\n\t\t\t</videopageinfo>\r\n\t\t</weappinfo>\r\n\t\t<statextstr />\r\n\t\t<mmreadershare>\r\n\t\t\t<itemshowtype>0</itemshowtype>\r\n\t\t\t<ispaysubscribe>0</ispaysubscribe>\r\n\t\t</mmreadershare>\r\n\t\t<musicShareItem>\r\n\t\t\t<musicDuration>0</musicDuration>\r\n\t\t</musicShareItem>\r\n\t\t<finderLiveProductShare>\r\n\t\t\t<finderLiveID><![CDATA[]]></finderLiveID>\r\n\t\t\t<finderUsername><![CDATA[]]></finderUsername>\r\n\t\t\t<finderObjectID><![CDATA[]]></finderObjectID>\r\n\t\t\t<finderNonceID><![CDATA[]]></finderNonceID>\r\n\t\t\t<liveStatus><![CDATA[]]></liveStatus>\r\n\t\t\t<appId><![CDATA[]]></appId>\r\n\t\t\t<pagePath><![CDATA[]]></pagePath>\r\n\t\t\t<productId><![CDATA[]]></productId>\r\n\t\t\t<coverUrl><![CDATA[]]></coverUrl>\r\n\t\t\t<productTitle><![CDATA[]]></productTitle>\r\n\t\t\t<marketPrice><![CDATA[0]]></marketPrice>\r\n\t\t\t<sellingPrice><![CDATA[0]]></sellingPrice>\r\n\t\t\t<platformHeadImg><![CDATA[]]></platformHeadImg>\r\n\t\t\t<platformName><![CDATA[]]></platformName>\r\n\t\t\t<shopWindowId><![CDATA[]]></shopWindowId>\r\n\t\t</finderLiveProductShare>\r\n\t\t<findernamecard>\r\n\t\t\t<username />\r\n\t\t\t<avatar><![CDATA[]]></avatar>\r\n\t\t\t<nickname />\r\n\t\t\t<auth_job />\r\n\t\t\t<auth_icon>0</auth_icon>\r\n\t\t\t<auth_icon_url />\r\n\t\t</findernamecard>\r\n\t\t<finderGuarantee>\r\n\t\t\t<scene><![CDATA[0]]></scene>\r\n\t\t</finderGuarantee>\r\n\t\t<directshare>0</directshare>\r\n\t\t<gamecenter>\r\n\t\t\t<namecard>\r\n\t\t\t\t<iconUrl />\r\n\t\t\t\t<name />\r\n\t\t\t\t<desc />\r\n\t\t\t\t<tail />\r\n\t\t\t\t<jumpUrl />\r\n\t\t\t</namecard>\r\n\t\t</gamecenter>\r\n\t\t<patMsg>\r\n\t\t\t<chatUser />\r\n\t\t\t<records>\r\n\t\t\t\t<recordNum>0</recordNum>\r\n\t\t\t</records>\r\n\t\t</patMsg>\r\n\t\t<secretmsg>\r\n\t\t\t<issecretmsg>0</issecretmsg>\r\n\t\t</secretmsg>\r\n\t\t<websearch>\r\n\t\t\t<rec_category>0</rec_category>\r\n\t\t\t<channelId>0</channelId>\r\n\t\t</websearch>\r\n\t</appmsg>\r\n\t<fromusername>wxid_8u55pl2uvpny22</fromusername>\r\n\t<scene>0</scene>\r\n\t<appinfo>\r\n\t\t<version>1</version>\r\n\t\t<appname />\r\n\t</appinfo>\r\n\t<commenturl />\r\n</msg>\r\n'}
Tay 09 09:36:48 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:48,480 [DEBUG]: urllib3.connectionpool (connectionpool._get_conn; connectionpool.py:266)
Tay 09 09:36:48 computer_name ehforwarderbot[173558]:     Resetting dropped connection: mp.weixin.qq.com
Tay 09 09:36:49 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:49,174 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:428)
Tay 09 09:36:49 computer_name ehforwarderbot[173558]:     http://mp.weixin.qq.com:80 "GET /s?__biz=MjM5OTYwOTM0Nw==&mid=2650229747&idx=1&sn=366826a0aa3a63dfb69a1ec08d6dbde3&chksm=bf3b3e9f884cb78903777eeab58841dfd16a4344276caa9b0b20dd39cfea3fa1b2d6df40e67c HTTP/1.1" 301 962
Tay 09 09:36:49 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:49,179 [DEBUG]: urllib3.connectionpool (connectionpool._get_conn; connectionpool.py:266)
Tay 09 09:36:49 computer_name ehforwarderbot[173558]:     Resetting dropped connection: mp.weixin.qq.com
Tay 09 09:36:50 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:50,943 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:428)
Tay 09 09:36:50 computer_name ehforwarderbot[173558]:     https://mp.weixin.qq.com:443 "GET /s?__biz=MjM5OTYwOTM0Nw==&mid=2650229747&idx=1&sn=366826a0aa3a63dfb69a1ec08d6dbde3&chksm=bf3b3e9f884cb78903777eeab58841dfd16a4344276caa9b0b20dd39cfea3fa1b2d6df40e67c HTTP/1.1" 200 57726
Tay 09 09:36:54 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:54,263 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:428)
Tay 09 09:36:54 computer_name ehforwarderbot[173558]:     https://api.telegra.ph:443 "POST /createPage HTTP/1.1" 200 58
Tay 09 09:36:54 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:54,264 [DEBUG]: plugins.catbaron.mp_instantview.MPInstantViewMiddleware (__init__.process_url; init.py:95)
Tay 09 09:36:54 computer_name ehforwarderbot[173558]:     Failed to process mp url!
Tay 09 09:36:54 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:54,264 [DEBUG]: plugins.catbaron.mp_instantview.MPInstantViewMiddleware (__init__.process_url; init.py:96)
Tay 09 09:36:54 computer_name ehforwarderbot[173558]:     'result'
Tay 09 09:36:54 computer_name ehforwarderbot[173558]: 2022-04-09 09:36:54,265 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:91)

**Comment by Rongronggg9** [comment]
```
Tay 09 09:36:54 computer_name ehforwarderbot[173558]: [https://api.telegra.ph:443](https://api.telegra.ph/) "POST /createPage HTTP/1.1" 200 58
```

`58` 表示 Telegraph API 返回的消息长度，这么短的长度，很明显是返回了一个错误，至于是啥，我猜是内容长度超限。

**Comment by QQ-War** [comment]
自己跑了一下， 最后print有点问题，回来再看看具体原因吧。

>>> page = tg.process_url('http://mp.weixin.qq.com/s?__biz=MjM5OTYwOTM0Nw==&amp;mid=2650229747&amp;idx=1&amp;sn=366826a0aa3a63dfb69a1ec08d6dbde3&amp;chksm=bf3b3e9f884cb78903777eeab58841dfd16a4344276caa9b0b20dd39cfea3fa1b2d6df40e67c#rd')
（这里没有问题）
>>> print(tg.publish(page['title'], page['author'], page['content']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcloud/.local/lib/python3.8/site-packages/efb_mp_instantview_middleware/telegraph.py", line 59, in publish
    return response['result']['url']
KeyError: 'result'
>>>

**Comment by Rongronggg9** [comment]
没有 result 就是 Telegraph API 不能成功生成文章，所以不会返回 result ，通常原因就是文章太长，超过 64KB

**Comment by QQ-War** [comment]
修改了下publich，直接返回respones，确实是太大了。这个有办法解决吗？

>>> print(tg.publish)
<bound method Telegraph.publish of <debug_QQ_war.Telegraph object at 0x7fef7e0d55b0>>
>>> print(tg.publish(page['title'], page['author'], page['content']))
{'ok': False, 'error': 'CONTENT_TOO_BIG'}
>>>

**Comment by Rongronggg9** [comment]
没有办法，这是硬性限制

**Comment by QQ-War** [comment]
写了个修改判断大小，如果超过65536就删除attrs属性的补丁。

**Comment by QQ-War** [comment]
还是没啥用，有的文章过于长，估计只能从把一篇分拆成几篇入手来考虑设计。但是Json要分拆真的好难。

**Comment by catbaron0** [comment]
see https://github.com/ehForwarderBot/efb-mp-instantview-middleware/pull/2
